<a href="https://colab.research.google.com/github/Gayathri-S-github/Codegnan-Datascience-Materials/blob/master/FDPDS_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
5+6

11

In [0]:
print("hello everyone")

hello everyone


In [0]:
a={"name":"Saketh","office":"codegnan"}
a

{'name': 'Saketh', 'office': 'codegnan'}

In [0]:
a=[1,2,2,'saketh',5.2]
print(a)
print(type(a))

[1, 2, 2, 'saketh', 5.2]
<class 'list'>


In [0]:
a[2] = 25

In [0]:
print(a)

[1, 2, 25, 'saketh', 5.2]


In [0]:
import math as m
m.sqrt(5)

2.23606797749979

In [0]:
m.e

2.718281828459045

In [0]:
m.pi

3.141592653589793

In [0]:
import array as a

In [0]:
b = a.array('i',[1,2,3])
b

array('i', [1, 2, 3])

In [0]:
import numpy as np
a = np.array([1,2,3])
a

array([1, 2, 3])

In [0]:
a.size

3

In [0]:
a = np.array([[1.,2,3],[4,5,6]])
a

array([[1., 2., 3.],
       [4., 5., 6.]])

In [0]:
a.shape

(2, 3)

In [0]:
a.size

6

In [0]:
a.itemsize

8

In [0]:
a

array([[1., 2., 3.],
       [4., 5., 6.]])

In [0]:
a[1]

array([4., 5., 6.])

In [0]:
import sys
S = range(1000)
print(S)
print(sys.getsizeof(50)*len(S))

range(0, 1000)
28000


In [0]:
D=np.arange(1000)
#print(D)
print(D.size*D.itemsize) #itemsize is how much memory occupied #size is no.of elements

8000


In [0]:
[1,2,3]+[4,5,6]

[1, 2, 3, 4, 5, 6]

In [0]:
a

array([[1., 2., 3.],
       [4., 5., 6.]])

In [0]:
b = np.array([[4,5,6],[7,8,9]])
print(b)
print(a+b)

[[4 5 6]
 [7 8 9]]
[[ 5.  7.  9.]
 [11. 13. 15.]]


In [0]:
data=np.random.rand(2,3) #range b/w 0-1
data

array([[0.41964762, 0.84502848, 0.58638438],
       [0.99558173, 0.94871029, 0.634139  ]])

In [0]:
data+b


array([[4.41964762, 5.84502848, 6.58638438],
       [7.99558173, 8.94871029, 9.634139  ]])

In [0]:
data-b

array([[-3.58035238, -4.15497152, -5.41361562],
       [-6.00441827, -7.05128971, -8.365861  ]])

In [0]:
data[:]

array([[0.41964762, 0.84502848, 0.58638438],
       [0.99558173, 0.94871029, 0.634139  ]])

In [0]:
data[0]

array([0.41964762, 0.84502848, 0.58638438])

In [0]:
data[0,1]

0.8450284778768886

In [0]:
a

array([[1., 2., 3.],
       [4., 5., 6.]])

In [0]:
c = np.mean(a)

In [0]:
c

3.5

In [0]:
d = np.var(a)
d

2.9166666666666665

In [0]:
np.std(a)

1.707825127659933

In [0]:
a

array([[1., 2., 3.],
       [4., 5., 6.]])

In [0]:
a[1:3]

array([[4., 5., 6.]])

In [0]:
import pandas as pd
a= pd.Series([1.,2,23])
print(a)

0     1.0
1     2.0
2    23.0
dtype: float64


In [0]:
a=pd.DataFrame([1,2,3])
a

0
0  1
1  2
2  3

In [0]:
a=pd.DataFrame(b,columns=['n','a','p'])
print(a)

   n  a  p
0  4  5  6
1  7  8  9


In [0]:
a.index

RangeIndex(start=0, stop=2, step=1)

In [0]:
a.columns

Index(['n', 'a', 'p'], dtype='object')

In [0]:
a.values

array([[4, 5, 6],
       [7, 8, 9]])

In [0]:
a['n']

0    4
1    7
Name: n, dtype: int64

In [0]:
a.dtypes

n    int64
a    int64
p    int64
dtype: object

In [0]:
a=pd.read_table("sample.txt",sep=',')
a

a b
0  1 2
1  3 4
2  5 6

In [0]:
a=pd.read_table("ex1.csv")
a

a,b,c,d,message
0   1,2,3,4,hello
1   5,6,7,8,world
2  9,10,11,12,foo

In [0]:
a=pd.read_table("ex1.csv",sep=',')
a

a   b   c   d message
0  1   2   3   4   hello
1  5   6   7   8   world
2  9  10  11  12     foo

In [0]:
a=pd.read_csv("ex1.csv",header=None)
a

0   1   2   3        4
0  a   b   c   d  message
1  1   2   3   4    hello
2  5   6   7   8    world
3  9  10  11  12      foo

In [0]:
tables = pd.read_html("fdic_failed_bank_list.html")
tables

[                             Bank Name  ...       Updated Date
 0                          Allied Bank  ...  November 17, 2016
 1         The Woodbury Banking Company  ...  November 17, 2016
 2               First CornerStone Bank  ...  September 6, 2016
 3                   Trust Company Bank  ...  September 6, 2016
 4           North Milwaukee State Bank  ...      June 16, 2016
 ..                                 ...  ...                ...
 542                 Superior Bank, FSB  ...    August 19, 2014
 543                Malta National Bank  ...  November 18, 2002
 544    First Alliance Bank & Trust Co.  ...  February 18, 2003
 545  National State Bank of Metropolis  ...     March 17, 2005
 546                   Bank of Honolulu  ...     March 17, 2005
 
 [547 rows x 7 columns]]

In [0]:
len(tables)

1

In [0]:
f=tables[0]
f.head()

Bank Name  ...       Updated Date
0                   Allied Bank  ...  November 17, 2016
1  The Woodbury Banking Company  ...  November 17, 2016
2        First CornerStone Bank  ...  September 6, 2016
3            Trust Company Bank  ...  September 6, 2016
4    North Milwaukee State Bank  ...      June 16, 2016

[5 rows x 7 columns]

In [0]:
f.head(2)

Bank Name  ...       Updated Date
0                   Allied Bank  ...  November 17, 2016
1  The Woodbury Banking Company  ...  November 17, 2016

[2 rows x 7 columns]

In [0]:
f.tail(5)

Bank Name  ...       Updated Date
542                 Superior Bank, FSB  ...    August 19, 2014
543                Malta National Bank  ...  November 18, 2002
544    First Alliance Bank & Trust Co.  ...  February 18, 2003
545  National State Bank of Metropolis  ...     March 17, 2005
546                   Bank of Honolulu  ...     March 17, 2005

[5 rows x 7 columns]

In [0]:
f.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 547 entries, 0 to 546
Data columns (total 7 columns):
 #   Column                 Non-Null Count  Dtype 
---  ------                 --------------  ----- 
 0   Bank Name              547 non-null    object
 1   City                   547 non-null    object
 2   ST                     547 non-null    object
 3   CERT                   547 non-null    int64 
 4   Acquiring Institution  547 non-null    object
 5   Closing Date           547 non-null    object
 6   Updated Date           547 non-null    object
dtypes: int64(1), object(6)
memory usage: 30.0+ KB


In [0]:
#null values
f.isnull().sum()

Bank Name                0
City                     0
ST                       0
CERT                     0
Acquiring Institution    0
Closing Date             0
Updated Date             0
dtype: int64